/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        paper: "hsl(var(--color-paper))",
        surface: "hsl(var(--color-surface))",
        "surface-soft": "hsl(var(--color-surface-soft))",
        hairline: "hsl(var(--color-hairline))",
        "surface-border": "hsl(var(--color-surface-border))",
        ink: "hsl(var(--color-ink))",
        "ink-secondary": "hsl(var(--color-ink-secondary))",
        "ink-tertiary": "hsl(var(--color-ink-tertiary))",
        primary: "hsl(var(--color-primary))",
        "primary-soft": "hsl(var(--color-primary-soft))",
        accent: "hsl(var(--color-accent))",
        "accent-soft": "hsl(var(--color-accent-soft))",
        "error-soft": "hsl(var(--color-error-soft))",
        "error-bright": "hsl(var(--color-error-bright))",
        success: "hsl(var(--color-success))",

        "primary-light": "#8C78FF",
        "primary-dark": "#482AC4",
        rose: "#FF5C8A",
        "plum-deep": "#2A1B4E",
        lavender: "#1B1826",
        blush: "#252132",
        "background-alt": "#1B1826",
        violet: "#8B5CF6",
        "violet-soft": "#8B5CF61F",
        amber: "#F59E0B",
        "amber-soft": "#F59E0B1F",
        "amber-dark": "#B45309",
        danger: "#E53E6B",
        emerald: "#10B981",
        "emerald-soft": "#10B9811F",
        muted: "#6B6480",
        "plum-border": "#2D2945",
      },
      fontFamily: {
        display: ["Urbanist_700Bold"],
        "display-bold": ["Urbanist_800ExtraBold"],
        "display-semi": ["Urbanist_600SemiBold"],
        ui: ["Urbanist_400Regular"],
        "ui-medium": ["Urbanist_500Medium"],
        "ui-semibold": ["Urbanist_600SemiBold"],
        "ui-bold": ["Urbanist_700Bold"],
      },
    },
  },
  plugins: [],
};
