/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#946BFF",
        "primary-light": "#8C78FF",
        "primary-dark": "#482AC4",
        "primary-soft": "#EFEAFF",
        accent: "#FF69B4",
        "accent-soft": "#FFE4F1",
        rose: "#FF5C8A",
        "plum-deep": "#2A1B4E",
        paper: "#100E17",
        surface: "#1B1826",
        "surface-soft": "#252132",
        hairline: "#2B2539",
        ink: "#F4F1FA",
        "ink-secondary": "#B3A8C9",
        "ink-tertiary": "#7E7396",
        lavender: "#1B1826",
        blush: "#252132",
        "background-alt": "#1B1826",
        "surface-border": "#2B2539",
        "error-soft": "#FDEAEE",
        "error-bright": "#F87171",
        success: "#22C55E",
        violet: "#8B5CF6",
        "violet-soft": "#8B5CF61F",
        amber: "#F59E0B",
        "amber-soft": "#F59E0B1F",
        "amber-dark": "#B45309",
        danger: "#E53E6B",
        emerald: "#10B981",
        "emerald-soft": "#10B9811F",
        muted: "#6B6480",
        "plum-border": "#2D2945",
      },
      fontFamily: {
        display: ["NunitoSans_700Bold"],
        "display-bold": ["NunitoSans_800ExtraBold"],
        "display-semi": ["NunitoSans_600SemiBold"],
        ui: ["NunitoSans_400Regular"],
        "ui-medium": ["NunitoSans_500Medium"],
        "ui-semibold": ["NunitoSans_600SemiBold"],
        "ui-bold": ["NunitoSans_700Bold"],
      },
    },
  },
  plugins: [],
};
